### ISSUE TITLE
Base step to go to a new tab throws error

### ISSUE THREAD

**Issue by paglajewel** [dougnoel/sentinel#223]
VerificationSteps.java

```
@Then("^I see a new tab open with the (.*) Page$")
    public static void openNewTab(String pageName) throws InterruptedException {
        PageManager.switchToNewWindow();
        pageName = pageName.replaceAll("\\s", "") + "Page";
        PageManager.setPage(pageName);
        PageManager.waitForPageLoad();
    }
```

**Error throws:**
com.dougnoel.sentinel.exceptions.NoSuchWindowException: Parent Window cannot be found. Please open a window and restart your test.
	at com.dougnoel.sentinel.pages.PageManager.switchToNewWindow(PageManager.java:198)
	at com.dougnoel.sentinel.steps.VerificationSteps.openNewTab(VerificationSteps.java:222)
	at ?.I see a new tab open with the Question Item Page(file:///C:/Users/shussain001/Documents/Codebase/sentinel.example/src/test/java/features/US67890%20Test%20Story%202.feature:37)

**Comment by dougnoel** [comment]
This step is a verification step used to move to an opened tab. It will fail if you did not open a new tab. What steps did you use to reproduce this?

@Then("^I see a new tab open with the (.*) Page$")
public static void i_see_a_new_tab_open_with_the_foo_Page​(java.lang.String pageName)
                                                   throws java.lang.Throwable
Opens the given pageName in a new window
Gherkin Examples:

I see a new tab open with the Home page
I see a new tab open with the Login page
I see a new tab open with the Google Maps page
Parameters:
pageName - String the page to open
Throws:
java.lang.Throwable - this exists so that any uncaught exceptions result in the test failing

https://dougnoel.github.io/sentinel/com/dougnoel/sentinel/steps/VerificationSteps.html#i_see_a_new_tab_open_with_the_foo_Page(java.lang.String)

**Comment by dougnoel** [comment]
I believe this was fixed.
